name: Release

on:
  release:
    types: [published]

jobs:
  build-sign:
    name: Build, Package, and Sign
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -r requirements-dev.txt
      - name: Run release pipeline
        run: ./scripts/release
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
      - name: Sign artifacts
        env:
          COSIGN_EXPERIMENTAL: '1'
        run: |
          for file in dist/*; do
            cosign sign-blob --yes "$file" --output-signature "$file.sig"
          done
      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
            sbom/sbom.json
sed -n '1,160p' .github/workflows/release.yml
